// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

package com.tianyi.zhang.multiplayer.snake.agents.messages;

public final class Packet {
  private Packet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.Update)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .messages.Update.ServerState serverState = 1;</code>
     */
    boolean hasServerState();
    /**
     * <code>optional .messages.Update.ServerState serverState = 1;</code>
     */
    com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ServerState getServerState();

    /**
     * <code>optional .messages.Update.ClientState clientState = 2;</code>
     */
    boolean hasClientState();
    /**
     * <code>optional .messages.Update.ClientState clientState = 2;</code>
     */
    com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ClientState getClientState();

    /**
     * <code>repeated .messages.Update.Snake snakes = 3;</code>
     */
    java.util.List<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake> 
        getSnakesList();
    /**
     * <code>repeated .messages.Update.Snake snakes = 3;</code>
     */
    com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake getSnakes(int index);
    /**
     * <code>repeated .messages.Update.Snake snakes = 3;</code>
     */
    int getSnakesCount();
    /**
     * <code>repeated .messages.Update.Snake snakes = 3;</code>
     */
    java.util.List<? extends com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.SnakeOrBuilder> 
        getSnakesOrBuilderList();
    /**
     * <code>repeated .messages.Update.Snake snakes = 3;</code>
     */
    com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.SnakeOrBuilder getSnakesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code messages.Update}
   */
  public  static final class Update extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:messages.Update)
      UpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Update.newBuilder() to construct.
    private Update(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Update() {
      serverState_ = 0;
      clientState_ = 0;
      snakes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Update(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ServerState value = com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ServerState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                serverState_ = rawValue;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ClientState value = com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ClientState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                clientState_ = rawValue;
              }
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                snakes_ = new java.util.ArrayList<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake>();
                mutable_bitField0_ |= 0x00000004;
              }
              snakes_.add(
                  input.readMessage(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          snakes_ = java.util.Collections.unmodifiableList(snakes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.class, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Builder.class);
    }

    /**
     * Protobuf enum {@code messages.Update.ServerState}
     */
    public enum ServerState
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>WAITING_FOR_CLIENTS = 0;</code>
       */
      WAITING_FOR_CLIENTS(0),
      /**
       * <code>SERVER_READY = 1;</code>
       */
      SERVER_READY(1),
      ;

      /**
       * <code>WAITING_FOR_CLIENTS = 0;</code>
       */
      public static final int WAITING_FOR_CLIENTS_VALUE = 0;
      /**
       * <code>SERVER_READY = 1;</code>
       */
      public static final int SERVER_READY_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ServerState valueOf(int value) {
        return forNumber(value);
      }

      public static ServerState forNumber(int value) {
        switch (value) {
          case 0: return WAITING_FOR_CLIENTS;
          case 1: return SERVER_READY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ServerState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ServerState> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ServerState>() {
              public ServerState findValueByNumber(int number) {
                return ServerState.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.getDescriptor().getEnumTypes().get(0);
      }

      private static final ServerState[] VALUES = values();

      public static ServerState valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ServerState(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:messages.Update.ServerState)
    }

    /**
     * Protobuf enum {@code messages.Update.ClientState}
     */
    public enum ClientState
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CLIENT_READY = 0;</code>
       */
      CLIENT_READY(0),
      ;

      /**
       * <code>CLIENT_READY = 0;</code>
       */
      public static final int CLIENT_READY_VALUE = 0;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ClientState valueOf(int value) {
        return forNumber(value);
      }

      public static ClientState forNumber(int value) {
        switch (value) {
          case 0: return CLIENT_READY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ClientState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ClientState> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ClientState>() {
              public ClientState findValueByNumber(int number) {
                return ClientState.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.getDescriptor().getEnumTypes().get(1);
      }

      private static final ClientState[] VALUES = values();

      public static ClientState valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ClientState(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:messages.Update.ClientState)
    }

    public interface SnakeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:messages.Update.Snake)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 dir = 1;</code>
       */
      boolean hasDir();
      /**
       * <code>optional int32 dir = 1;</code>
       */
      int getDir();

      /**
       * <code>repeated int32 coords = 2;</code>
       */
      java.util.List<java.lang.Integer> getCoordsList();
      /**
       * <code>repeated int32 coords = 2;</code>
       */
      int getCoordsCount();
      /**
       * <code>repeated int32 coords = 2;</code>
       */
      int getCoords(int index);
    }
    /**
     * Protobuf type {@code messages.Update.Snake}
     */
    public  static final class Snake extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:messages.Update.Snake)
        SnakeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Snake.newBuilder() to construct.
      private Snake(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Snake() {
        dir_ = 0;
        coords_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Snake(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                dir_ = input.readInt32();
                break;
              }
              case 16: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  coords_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000002;
                }
                coords_.add(input.readInt32());
                break;
              }
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                  coords_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000002;
                }
                while (input.getBytesUntilLimit() > 0) {
                  coords_.add(input.readInt32());
                }
                input.popLimit(limit);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            coords_ = java.util.Collections.unmodifiableList(coords_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_Snake_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_Snake_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.class, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.Builder.class);
      }

      private int bitField0_;
      public static final int DIR_FIELD_NUMBER = 1;
      private int dir_;
      /**
       * <code>optional int32 dir = 1;</code>
       */
      public boolean hasDir() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 dir = 1;</code>
       */
      public int getDir() {
        return dir_;
      }

      public static final int COORDS_FIELD_NUMBER = 2;
      private java.util.List<java.lang.Integer> coords_;
      /**
       * <code>repeated int32 coords = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getCoordsList() {
        return coords_;
      }
      /**
       * <code>repeated int32 coords = 2;</code>
       */
      public int getCoordsCount() {
        return coords_.size();
      }
      /**
       * <code>repeated int32 coords = 2;</code>
       */
      public int getCoords(int index) {
        return coords_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, dir_);
        }
        for (int i = 0; i < coords_.size(); i++) {
          output.writeInt32(2, coords_.get(i));
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, dir_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < coords_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(coords_.get(i));
          }
          size += dataSize;
          size += 1 * getCoordsList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake)) {
          return super.equals(obj);
        }
        com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake other = (com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake) obj;

        boolean result = true;
        result = result && (hasDir() == other.hasDir());
        if (hasDir()) {
          result = result && (getDir()
              == other.getDir());
        }
        result = result && getCoordsList()
            .equals(other.getCoordsList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasDir()) {
          hash = (37 * hash) + DIR_FIELD_NUMBER;
          hash = (53 * hash) + getDir();
        }
        if (getCoordsCount() > 0) {
          hash = (37 * hash) + COORDS_FIELD_NUMBER;
          hash = (53 * hash) + getCoordsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code messages.Update.Snake}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:messages.Update.Snake)
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.SnakeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_Snake_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_Snake_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.class, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.Builder.class);
        }

        // Construct using com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          dir_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          coords_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_Snake_descriptor;
        }

        public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake getDefaultInstanceForType() {
          return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.getDefaultInstance();
        }

        public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake build() {
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake buildPartial() {
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake result = new com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.dir_ = dir_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            coords_ = java.util.Collections.unmodifiableList(coords_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.coords_ = coords_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake) {
            return mergeFrom((com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake other) {
          if (other == com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.getDefaultInstance()) return this;
          if (other.hasDir()) {
            setDir(other.getDir());
          }
          if (!other.coords_.isEmpty()) {
            if (coords_.isEmpty()) {
              coords_ = other.coords_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCoordsIsMutable();
              coords_.addAll(other.coords_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int dir_ ;
        /**
         * <code>optional int32 dir = 1;</code>
         */
        public boolean hasDir() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 dir = 1;</code>
         */
        public int getDir() {
          return dir_;
        }
        /**
         * <code>optional int32 dir = 1;</code>
         */
        public Builder setDir(int value) {
          bitField0_ |= 0x00000001;
          dir_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 dir = 1;</code>
         */
        public Builder clearDir() {
          bitField0_ = (bitField0_ & ~0x00000001);
          dir_ = 0;
          onChanged();
          return this;
        }

        private java.util.List<java.lang.Integer> coords_ = java.util.Collections.emptyList();
        private void ensureCoordsIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            coords_ = new java.util.ArrayList<java.lang.Integer>(coords_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated int32 coords = 2;</code>
         */
        public java.util.List<java.lang.Integer>
            getCoordsList() {
          return java.util.Collections.unmodifiableList(coords_);
        }
        /**
         * <code>repeated int32 coords = 2;</code>
         */
        public int getCoordsCount() {
          return coords_.size();
        }
        /**
         * <code>repeated int32 coords = 2;</code>
         */
        public int getCoords(int index) {
          return coords_.get(index);
        }
        /**
         * <code>repeated int32 coords = 2;</code>
         */
        public Builder setCoords(
            int index, int value) {
          ensureCoordsIsMutable();
          coords_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 coords = 2;</code>
         */
        public Builder addCoords(int value) {
          ensureCoordsIsMutable();
          coords_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 coords = 2;</code>
         */
        public Builder addAllCoords(
            java.lang.Iterable<? extends java.lang.Integer> values) {
          ensureCoordsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, coords_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 coords = 2;</code>
         */
        public Builder clearCoords() {
          coords_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:messages.Update.Snake)
      }

      // @@protoc_insertion_point(class_scope:messages.Update.Snake)
      private static final com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake();
      }

      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Snake>
          PARSER = new com.google.protobuf.AbstractParser<Snake>() {
        public Snake parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Snake(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Snake> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Snake> getParserForType() {
        return PARSER;
      }

      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int SERVERSTATE_FIELD_NUMBER = 1;
    private int serverState_;
    /**
     * <code>optional .messages.Update.ServerState serverState = 1;</code>
     */
    public boolean hasServerState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .messages.Update.ServerState serverState = 1;</code>
     */
    public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ServerState getServerState() {
      com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ServerState result = com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ServerState.valueOf(serverState_);
      return result == null ? com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ServerState.WAITING_FOR_CLIENTS : result;
    }

    public static final int CLIENTSTATE_FIELD_NUMBER = 2;
    private int clientState_;
    /**
     * <code>optional .messages.Update.ClientState clientState = 2;</code>
     */
    public boolean hasClientState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .messages.Update.ClientState clientState = 2;</code>
     */
    public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ClientState getClientState() {
      com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ClientState result = com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ClientState.valueOf(clientState_);
      return result == null ? com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ClientState.CLIENT_READY : result;
    }

    public static final int SNAKES_FIELD_NUMBER = 3;
    private java.util.List<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake> snakes_;
    /**
     * <code>repeated .messages.Update.Snake snakes = 3;</code>
     */
    public java.util.List<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake> getSnakesList() {
      return snakes_;
    }
    /**
     * <code>repeated .messages.Update.Snake snakes = 3;</code>
     */
    public java.util.List<? extends com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.SnakeOrBuilder> 
        getSnakesOrBuilderList() {
      return snakes_;
    }
    /**
     * <code>repeated .messages.Update.Snake snakes = 3;</code>
     */
    public int getSnakesCount() {
      return snakes_.size();
    }
    /**
     * <code>repeated .messages.Update.Snake snakes = 3;</code>
     */
    public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake getSnakes(int index) {
      return snakes_.get(index);
    }
    /**
     * <code>repeated .messages.Update.Snake snakes = 3;</code>
     */
    public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.SnakeOrBuilder getSnakesOrBuilder(
        int index) {
      return snakes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, serverState_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, clientState_);
      }
      for (int i = 0; i < snakes_.size(); i++) {
        output.writeMessage(3, snakes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, serverState_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, clientState_);
      }
      for (int i = 0; i < snakes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, snakes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update)) {
        return super.equals(obj);
      }
      com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update other = (com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update) obj;

      boolean result = true;
      result = result && (hasServerState() == other.hasServerState());
      if (hasServerState()) {
        result = result && serverState_ == other.serverState_;
      }
      result = result && (hasClientState() == other.hasClientState());
      if (hasClientState()) {
        result = result && clientState_ == other.clientState_;
      }
      result = result && getSnakesList()
          .equals(other.getSnakesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasServerState()) {
        hash = (37 * hash) + SERVERSTATE_FIELD_NUMBER;
        hash = (53 * hash) + serverState_;
      }
      if (hasClientState()) {
        hash = (37 * hash) + CLIENTSTATE_FIELD_NUMBER;
        hash = (53 * hash) + clientState_;
      }
      if (getSnakesCount() > 0) {
        hash = (37 * hash) + SNAKES_FIELD_NUMBER;
        hash = (53 * hash) + getSnakesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.Update}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.Update)
        com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.UpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.class, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Builder.class);
      }

      // Construct using com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSnakesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        serverState_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        clientState_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (snakesBuilder_ == null) {
          snakes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          snakesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_descriptor;
      }

      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update getDefaultInstanceForType() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.getDefaultInstance();
      }

      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update build() {
        com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update buildPartial() {
        com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update result = new com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverState_ = serverState_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientState_ = clientState_;
        if (snakesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            snakes_ = java.util.Collections.unmodifiableList(snakes_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.snakes_ = snakes_;
        } else {
          result.snakes_ = snakesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update) {
          return mergeFrom((com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update other) {
        if (other == com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.getDefaultInstance()) return this;
        if (other.hasServerState()) {
          setServerState(other.getServerState());
        }
        if (other.hasClientState()) {
          setClientState(other.getClientState());
        }
        if (snakesBuilder_ == null) {
          if (!other.snakes_.isEmpty()) {
            if (snakes_.isEmpty()) {
              snakes_ = other.snakes_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSnakesIsMutable();
              snakes_.addAll(other.snakes_);
            }
            onChanged();
          }
        } else {
          if (!other.snakes_.isEmpty()) {
            if (snakesBuilder_.isEmpty()) {
              snakesBuilder_.dispose();
              snakesBuilder_ = null;
              snakes_ = other.snakes_;
              bitField0_ = (bitField0_ & ~0x00000004);
              snakesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSnakesFieldBuilder() : null;
            } else {
              snakesBuilder_.addAllMessages(other.snakes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int serverState_ = 0;
      /**
       * <code>optional .messages.Update.ServerState serverState = 1;</code>
       */
      public boolean hasServerState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .messages.Update.ServerState serverState = 1;</code>
       */
      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ServerState getServerState() {
        com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ServerState result = com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ServerState.valueOf(serverState_);
        return result == null ? com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ServerState.WAITING_FOR_CLIENTS : result;
      }
      /**
       * <code>optional .messages.Update.ServerState serverState = 1;</code>
       */
      public Builder setServerState(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ServerState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        serverState_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .messages.Update.ServerState serverState = 1;</code>
       */
      public Builder clearServerState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverState_ = 0;
        onChanged();
        return this;
      }

      private int clientState_ = 0;
      /**
       * <code>optional .messages.Update.ClientState clientState = 2;</code>
       */
      public boolean hasClientState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .messages.Update.ClientState clientState = 2;</code>
       */
      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ClientState getClientState() {
        com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ClientState result = com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ClientState.valueOf(clientState_);
        return result == null ? com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ClientState.CLIENT_READY : result;
      }
      /**
       * <code>optional .messages.Update.ClientState clientState = 2;</code>
       */
      public Builder setClientState(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.ClientState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        clientState_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .messages.Update.ClientState clientState = 2;</code>
       */
      public Builder clearClientState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientState_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake> snakes_ =
        java.util.Collections.emptyList();
      private void ensureSnakesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          snakes_ = new java.util.ArrayList<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake>(snakes_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.Builder, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.SnakeOrBuilder> snakesBuilder_;

      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public java.util.List<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake> getSnakesList() {
        if (snakesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(snakes_);
        } else {
          return snakesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public int getSnakesCount() {
        if (snakesBuilder_ == null) {
          return snakes_.size();
        } else {
          return snakesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake getSnakes(int index) {
        if (snakesBuilder_ == null) {
          return snakes_.get(index);
        } else {
          return snakesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public Builder setSnakes(
          int index, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake value) {
        if (snakesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnakesIsMutable();
          snakes_.set(index, value);
          onChanged();
        } else {
          snakesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public Builder setSnakes(
          int index, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.Builder builderForValue) {
        if (snakesBuilder_ == null) {
          ensureSnakesIsMutable();
          snakes_.set(index, builderForValue.build());
          onChanged();
        } else {
          snakesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public Builder addSnakes(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake value) {
        if (snakesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnakesIsMutable();
          snakes_.add(value);
          onChanged();
        } else {
          snakesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public Builder addSnakes(
          int index, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake value) {
        if (snakesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnakesIsMutable();
          snakes_.add(index, value);
          onChanged();
        } else {
          snakesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public Builder addSnakes(
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.Builder builderForValue) {
        if (snakesBuilder_ == null) {
          ensureSnakesIsMutable();
          snakes_.add(builderForValue.build());
          onChanged();
        } else {
          snakesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public Builder addSnakes(
          int index, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.Builder builderForValue) {
        if (snakesBuilder_ == null) {
          ensureSnakesIsMutable();
          snakes_.add(index, builderForValue.build());
          onChanged();
        } else {
          snakesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public Builder addAllSnakes(
          java.lang.Iterable<? extends com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake> values) {
        if (snakesBuilder_ == null) {
          ensureSnakesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, snakes_);
          onChanged();
        } else {
          snakesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public Builder clearSnakes() {
        if (snakesBuilder_ == null) {
          snakes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          snakesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public Builder removeSnakes(int index) {
        if (snakesBuilder_ == null) {
          ensureSnakesIsMutable();
          snakes_.remove(index);
          onChanged();
        } else {
          snakesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.Builder getSnakesBuilder(
          int index) {
        return getSnakesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.SnakeOrBuilder getSnakesOrBuilder(
          int index) {
        if (snakesBuilder_ == null) {
          return snakes_.get(index);  } else {
          return snakesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public java.util.List<? extends com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.SnakeOrBuilder> 
           getSnakesOrBuilderList() {
        if (snakesBuilder_ != null) {
          return snakesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(snakes_);
        }
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.Builder addSnakesBuilder() {
        return getSnakesFieldBuilder().addBuilder(
            com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.getDefaultInstance());
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.Builder addSnakesBuilder(
          int index) {
        return getSnakesFieldBuilder().addBuilder(
            index, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.getDefaultInstance());
      }
      /**
       * <code>repeated .messages.Update.Snake snakes = 3;</code>
       */
      public java.util.List<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.Builder> 
           getSnakesBuilderList() {
        return getSnakesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.Builder, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.SnakeOrBuilder> 
          getSnakesFieldBuilder() {
        if (snakesBuilder_ == null) {
          snakesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Snake.Builder, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.SnakeOrBuilder>(
                  snakes_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          snakes_ = null;
        }
        return snakesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:messages.Update)
    }

    // @@protoc_insertion_point(class_scope:messages.Update)
    private static final com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update();
    }

    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Update>
        PARSER = new com.google.protobuf.AbstractParser<Update>() {
      public Update parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Update(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Update> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Update> getParserForType() {
      return PARSER;
    }

    public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Update_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_Update_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Update_Snake_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_Update_Snake_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014packet.proto\022\010messages\"\227\002\n\006Update\0221\n\013s" +
      "erverState\030\001 \001(\0162\034.messages.Update.Serve" +
      "rState\0221\n\013clientState\030\002 \001(\0162\034.messages.U" +
      "pdate.ClientState\022&\n\006snakes\030\003 \003(\0132\026.mess" +
      "ages.Update.Snake\032$\n\005Snake\022\013\n\003dir\030\001 \001(\005\022" +
      "\016\n\006coords\030\002 \003(\005\"8\n\013ServerState\022\027\n\023WAITIN" +
      "G_FOR_CLIENTS\020\000\022\020\n\014SERVER_READY\020\001\"\037\n\013Cli" +
      "entState\022\020\n\014CLIENT_READY\020\000B<\n2com.tianyi" +
      ".zhang.multiplayer.snake.agents.messages" +
      "B\006Packet"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_messages_Update_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_Update_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_Update_descriptor,
        new java.lang.String[] { "ServerState", "ClientState", "Snakes", });
    internal_static_messages_Update_Snake_descriptor =
      internal_static_messages_Update_descriptor.getNestedTypes().get(0);
    internal_static_messages_Update_Snake_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_Update_Snake_descriptor,
        new java.lang.String[] { "Dir", "Coords", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
