// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

package com.tianyi.zhang.multiplayer.snake.agents.messages;

public final class Packet {
  private Packet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.Update)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .messages.Update.PState state = 1;</code>
     */
    boolean hasState();
    /**
     * <code>required .messages.Update.PState state = 1;</code>
     */
    com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PState getState();

    /**
     * <code>required int32 version = 2;</code>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 2;</code>
     */
    int getVersion();

    /**
     * <code>required int64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    long getTimestamp();

    /**
     * <code>repeated .messages.Update.PSnake snakes = 4;</code>
     */
    java.util.List<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake> 
        getSnakesList();
    /**
     * <code>repeated .messages.Update.PSnake snakes = 4;</code>
     */
    com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake getSnakes(int index);
    /**
     * <code>repeated .messages.Update.PSnake snakes = 4;</code>
     */
    int getSnakesCount();
    /**
     * <code>repeated .messages.Update.PSnake snakes = 4;</code>
     */
    java.util.List<? extends com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnakeOrBuilder> 
        getSnakesOrBuilderList();
    /**
     * <code>repeated .messages.Update.PSnake snakes = 4;</code>
     */
    com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnakeOrBuilder getSnakesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code messages.Update}
   */
  public  static final class Update extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:messages.Update)
      UpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Update.newBuilder() to construct.
    private Update(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Update() {
      state_ = 0;
      version_ = 0;
      timestamp_ = 0L;
      snakes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Update(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PState value = com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                state_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              version_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                snakes_ = new java.util.ArrayList<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake>();
                mutable_bitField0_ |= 0x00000008;
              }
              snakes_.add(
                  input.readMessage(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          snakes_ = java.util.Collections.unmodifiableList(snakes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.class, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Builder.class);
    }

    /**
     * Protobuf enum {@code messages.Update.PState}
     */
    public enum PState
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>READY = 0;</code>
       */
      READY(0),
      /**
       * <code>GAME_IN_PROGRESS = 1;</code>
       */
      GAME_IN_PROGRESS(1),
      ;

      /**
       * <code>READY = 0;</code>
       */
      public static final int READY_VALUE = 0;
      /**
       * <code>GAME_IN_PROGRESS = 1;</code>
       */
      public static final int GAME_IN_PROGRESS_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PState valueOf(int value) {
        return forNumber(value);
      }

      public static PState forNumber(int value) {
        switch (value) {
          case 0: return READY;
          case 1: return GAME_IN_PROGRESS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PState> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PState>() {
              public PState findValueByNumber(int number) {
                return PState.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.getDescriptor().getEnumTypes().get(0);
      }

      private static final PState[] VALUES = values();

      public static PState valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PState(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:messages.Update.PState)
    }

    public interface PSnakeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:messages.Update.PSnake)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required int32 id = 1;</code>
       */
      int getId();

      /**
       * <code>required int32 lastInputId = 2;</code>
       */
      boolean hasLastInputId();
      /**
       * <code>required int32 lastInputId = 2;</code>
       */
      int getLastInputId();

      /**
       * <code>required int32 direction = 3;</code>
       */
      boolean hasDirection();
      /**
       * <code>required int32 direction = 3;</code>
       */
      int getDirection();

      /**
       * <code>repeated int32 coords = 4;</code>
       */
      java.util.List<java.lang.Integer> getCoordsList();
      /**
       * <code>repeated int32 coords = 4;</code>
       */
      int getCoordsCount();
      /**
       * <code>repeated int32 coords = 4;</code>
       */
      int getCoords(int index);
    }
    /**
     * Protobuf type {@code messages.Update.PSnake}
     */
    public  static final class PSnake extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:messages.Update.PSnake)
        PSnakeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PSnake.newBuilder() to construct.
      private PSnake(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PSnake() {
        id_ = 0;
        lastInputId_ = 0;
        direction_ = 0;
        coords_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private PSnake(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                lastInputId_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                direction_ = input.readInt32();
                break;
              }
              case 32: {
                if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                  coords_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000008;
                }
                coords_.add(input.readInt32());
                break;
              }
              case 34: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                  coords_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000008;
                }
                while (input.getBytesUntilLimit() > 0) {
                  coords_.add(input.readInt32());
                }
                input.popLimit(limit);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
            coords_ = java.util.Collections.unmodifiableList(coords_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_PSnake_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_PSnake_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.class, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.Builder.class);
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      public static final int LASTINPUTID_FIELD_NUMBER = 2;
      private int lastInputId_;
      /**
       * <code>required int32 lastInputId = 2;</code>
       */
      public boolean hasLastInputId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 lastInputId = 2;</code>
       */
      public int getLastInputId() {
        return lastInputId_;
      }

      public static final int DIRECTION_FIELD_NUMBER = 3;
      private int direction_;
      /**
       * <code>required int32 direction = 3;</code>
       */
      public boolean hasDirection() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 direction = 3;</code>
       */
      public int getDirection() {
        return direction_;
      }

      public static final int COORDS_FIELD_NUMBER = 4;
      private java.util.List<java.lang.Integer> coords_;
      /**
       * <code>repeated int32 coords = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getCoordsList() {
        return coords_;
      }
      /**
       * <code>repeated int32 coords = 4;</code>
       */
      public int getCoordsCount() {
        return coords_.size();
      }
      /**
       * <code>repeated int32 coords = 4;</code>
       */
      public int getCoords(int index) {
        return coords_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLastInputId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDirection()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, lastInputId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, direction_);
        }
        for (int i = 0; i < coords_.size(); i++) {
          output.writeInt32(4, coords_.get(i));
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, lastInputId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, direction_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < coords_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(coords_.get(i));
          }
          size += dataSize;
          size += 1 * getCoordsList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake)) {
          return super.equals(obj);
        }
        com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake other = (com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake) obj;

        boolean result = true;
        result = result && (hasId() == other.hasId());
        if (hasId()) {
          result = result && (getId()
              == other.getId());
        }
        result = result && (hasLastInputId() == other.hasLastInputId());
        if (hasLastInputId()) {
          result = result && (getLastInputId()
              == other.getLastInputId());
        }
        result = result && (hasDirection() == other.hasDirection());
        if (hasDirection()) {
          result = result && (getDirection()
              == other.getDirection());
        }
        result = result && getCoordsList()
            .equals(other.getCoordsList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasId()) {
          hash = (37 * hash) + ID_FIELD_NUMBER;
          hash = (53 * hash) + getId();
        }
        if (hasLastInputId()) {
          hash = (37 * hash) + LASTINPUTID_FIELD_NUMBER;
          hash = (53 * hash) + getLastInputId();
        }
        if (hasDirection()) {
          hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
          hash = (53 * hash) + getDirection();
        }
        if (getCoordsCount() > 0) {
          hash = (37 * hash) + COORDS_FIELD_NUMBER;
          hash = (53 * hash) + getCoordsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code messages.Update.PSnake}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:messages.Update.PSnake)
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnakeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_PSnake_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_PSnake_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.class, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.Builder.class);
        }

        // Construct using com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          lastInputId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          direction_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          coords_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_PSnake_descriptor;
        }

        public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake getDefaultInstanceForType() {
          return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.getDefaultInstance();
        }

        public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake build() {
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake buildPartial() {
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake result = new com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.lastInputId_ = lastInputId_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.direction_ = direction_;
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            coords_ = java.util.Collections.unmodifiableList(coords_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.coords_ = coords_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake) {
            return mergeFrom((com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake other) {
          if (other == com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasLastInputId()) {
            setLastInputId(other.getLastInputId());
          }
          if (other.hasDirection()) {
            setDirection(other.getDirection());
          }
          if (!other.coords_.isEmpty()) {
            if (coords_.isEmpty()) {
              coords_ = other.coords_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureCoordsIsMutable();
              coords_.addAll(other.coords_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            return false;
          }
          if (!hasLastInputId()) {
            return false;
          }
          if (!hasDirection()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int id_ ;
        /**
         * <code>required int32 id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }

        private int lastInputId_ ;
        /**
         * <code>required int32 lastInputId = 2;</code>
         */
        public boolean hasLastInputId() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 lastInputId = 2;</code>
         */
        public int getLastInputId() {
          return lastInputId_;
        }
        /**
         * <code>required int32 lastInputId = 2;</code>
         */
        public Builder setLastInputId(int value) {
          bitField0_ |= 0x00000002;
          lastInputId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 lastInputId = 2;</code>
         */
        public Builder clearLastInputId() {
          bitField0_ = (bitField0_ & ~0x00000002);
          lastInputId_ = 0;
          onChanged();
          return this;
        }

        private int direction_ ;
        /**
         * <code>required int32 direction = 3;</code>
         */
        public boolean hasDirection() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required int32 direction = 3;</code>
         */
        public int getDirection() {
          return direction_;
        }
        /**
         * <code>required int32 direction = 3;</code>
         */
        public Builder setDirection(int value) {
          bitField0_ |= 0x00000004;
          direction_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 direction = 3;</code>
         */
        public Builder clearDirection() {
          bitField0_ = (bitField0_ & ~0x00000004);
          direction_ = 0;
          onChanged();
          return this;
        }

        private java.util.List<java.lang.Integer> coords_ = java.util.Collections.emptyList();
        private void ensureCoordsIsMutable() {
          if (!((bitField0_ & 0x00000008) == 0x00000008)) {
            coords_ = new java.util.ArrayList<java.lang.Integer>(coords_);
            bitField0_ |= 0x00000008;
           }
        }
        /**
         * <code>repeated int32 coords = 4;</code>
         */
        public java.util.List<java.lang.Integer>
            getCoordsList() {
          return java.util.Collections.unmodifiableList(coords_);
        }
        /**
         * <code>repeated int32 coords = 4;</code>
         */
        public int getCoordsCount() {
          return coords_.size();
        }
        /**
         * <code>repeated int32 coords = 4;</code>
         */
        public int getCoords(int index) {
          return coords_.get(index);
        }
        /**
         * <code>repeated int32 coords = 4;</code>
         */
        public Builder setCoords(
            int index, int value) {
          ensureCoordsIsMutable();
          coords_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 coords = 4;</code>
         */
        public Builder addCoords(int value) {
          ensureCoordsIsMutable();
          coords_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 coords = 4;</code>
         */
        public Builder addAllCoords(
            java.lang.Iterable<? extends java.lang.Integer> values) {
          ensureCoordsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, coords_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 coords = 4;</code>
         */
        public Builder clearCoords() {
          coords_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:messages.Update.PSnake)
      }

      // @@protoc_insertion_point(class_scope:messages.Update.PSnake)
      private static final com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake();
      }

      public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<PSnake>
          PARSER = new com.google.protobuf.AbstractParser<PSnake>() {
        public PSnake parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PSnake(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PSnake> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PSnake> getParserForType() {
        return PARSER;
      }

      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;
    /**
     * <code>required .messages.Update.PState state = 1;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .messages.Update.PState state = 1;</code>
     */
    public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PState getState() {
      com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PState result = com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PState.valueOf(state_);
      return result == null ? com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PState.READY : result;
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <code>required int32 version = 2;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 version = 2;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int SNAKES_FIELD_NUMBER = 4;
    private java.util.List<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake> snakes_;
    /**
     * <code>repeated .messages.Update.PSnake snakes = 4;</code>
     */
    public java.util.List<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake> getSnakesList() {
      return snakes_;
    }
    /**
     * <code>repeated .messages.Update.PSnake snakes = 4;</code>
     */
    public java.util.List<? extends com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnakeOrBuilder> 
        getSnakesOrBuilderList() {
      return snakes_;
    }
    /**
     * <code>repeated .messages.Update.PSnake snakes = 4;</code>
     */
    public int getSnakesCount() {
      return snakes_.size();
    }
    /**
     * <code>repeated .messages.Update.PSnake snakes = 4;</code>
     */
    public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake getSnakes(int index) {
      return snakes_.get(index);
    }
    /**
     * <code>repeated .messages.Update.PSnake snakes = 4;</code>
     */
    public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnakeOrBuilder getSnakesOrBuilder(
        int index) {
      return snakes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSnakesCount(); i++) {
        if (!getSnakes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, version_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      for (int i = 0; i < snakes_.size(); i++) {
        output.writeMessage(4, snakes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      for (int i = 0; i < snakes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, snakes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update)) {
        return super.equals(obj);
      }
      com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update other = (com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update) obj;

      boolean result = true;
      result = result && (hasState() == other.hasState());
      if (hasState()) {
        result = result && state_ == other.state_;
      }
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && (getVersion()
            == other.getVersion());
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && getSnakesList()
          .equals(other.getSnakesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + state_;
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (getSnakesCount() > 0) {
        hash = (37 * hash) + SNAKES_FIELD_NUMBER;
        hash = (53 * hash) + getSnakesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.Update}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.Update)
        com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.UpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.class, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.Builder.class);
      }

      // Construct using com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSnakesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (snakesBuilder_ == null) {
          snakes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          snakesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.internal_static_messages_Update_descriptor;
      }

      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update getDefaultInstanceForType() {
        return com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.getDefaultInstance();
      }

      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update build() {
        com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update buildPartial() {
        com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update result = new com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (snakesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            snakes_ = java.util.Collections.unmodifiableList(snakes_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.snakes_ = snakes_;
        } else {
          result.snakes_ = snakesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update) {
          return mergeFrom((com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update other) {
        if (other == com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (snakesBuilder_ == null) {
          if (!other.snakes_.isEmpty()) {
            if (snakes_.isEmpty()) {
              snakes_ = other.snakes_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureSnakesIsMutable();
              snakes_.addAll(other.snakes_);
            }
            onChanged();
          }
        } else {
          if (!other.snakes_.isEmpty()) {
            if (snakesBuilder_.isEmpty()) {
              snakesBuilder_.dispose();
              snakesBuilder_ = null;
              snakes_ = other.snakes_;
              bitField0_ = (bitField0_ & ~0x00000008);
              snakesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSnakesFieldBuilder() : null;
            } else {
              snakesBuilder_.addAllMessages(other.snakes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasState()) {
          return false;
        }
        if (!hasVersion()) {
          return false;
        }
        if (!hasTimestamp()) {
          return false;
        }
        for (int i = 0; i < getSnakesCount(); i++) {
          if (!getSnakes(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int state_ = 0;
      /**
       * <code>required .messages.Update.PState state = 1;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .messages.Update.PState state = 1;</code>
       */
      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PState getState() {
        com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PState result = com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PState.valueOf(state_);
        return result == null ? com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PState.READY : result;
      }
      /**
       * <code>required .messages.Update.PState state = 1;</code>
       */
      public Builder setState(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .messages.Update.PState state = 1;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>required int32 version = 2;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 version = 2;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 2;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 2;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake> snakes_ =
        java.util.Collections.emptyList();
      private void ensureSnakesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          snakes_ = new java.util.ArrayList<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake>(snakes_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.Builder, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnakeOrBuilder> snakesBuilder_;

      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public java.util.List<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake> getSnakesList() {
        if (snakesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(snakes_);
        } else {
          return snakesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public int getSnakesCount() {
        if (snakesBuilder_ == null) {
          return snakes_.size();
        } else {
          return snakesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake getSnakes(int index) {
        if (snakesBuilder_ == null) {
          return snakes_.get(index);
        } else {
          return snakesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public Builder setSnakes(
          int index, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake value) {
        if (snakesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnakesIsMutable();
          snakes_.set(index, value);
          onChanged();
        } else {
          snakesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public Builder setSnakes(
          int index, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.Builder builderForValue) {
        if (snakesBuilder_ == null) {
          ensureSnakesIsMutable();
          snakes_.set(index, builderForValue.build());
          onChanged();
        } else {
          snakesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public Builder addSnakes(com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake value) {
        if (snakesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnakesIsMutable();
          snakes_.add(value);
          onChanged();
        } else {
          snakesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public Builder addSnakes(
          int index, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake value) {
        if (snakesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSnakesIsMutable();
          snakes_.add(index, value);
          onChanged();
        } else {
          snakesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public Builder addSnakes(
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.Builder builderForValue) {
        if (snakesBuilder_ == null) {
          ensureSnakesIsMutable();
          snakes_.add(builderForValue.build());
          onChanged();
        } else {
          snakesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public Builder addSnakes(
          int index, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.Builder builderForValue) {
        if (snakesBuilder_ == null) {
          ensureSnakesIsMutable();
          snakes_.add(index, builderForValue.build());
          onChanged();
        } else {
          snakesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public Builder addAllSnakes(
          java.lang.Iterable<? extends com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake> values) {
        if (snakesBuilder_ == null) {
          ensureSnakesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, snakes_);
          onChanged();
        } else {
          snakesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public Builder clearSnakes() {
        if (snakesBuilder_ == null) {
          snakes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          snakesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public Builder removeSnakes(int index) {
        if (snakesBuilder_ == null) {
          ensureSnakesIsMutable();
          snakes_.remove(index);
          onChanged();
        } else {
          snakesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.Builder getSnakesBuilder(
          int index) {
        return getSnakesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnakeOrBuilder getSnakesOrBuilder(
          int index) {
        if (snakesBuilder_ == null) {
          return snakes_.get(index);  } else {
          return snakesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public java.util.List<? extends com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnakeOrBuilder> 
           getSnakesOrBuilderList() {
        if (snakesBuilder_ != null) {
          return snakesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(snakes_);
        }
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.Builder addSnakesBuilder() {
        return getSnakesFieldBuilder().addBuilder(
            com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.getDefaultInstance());
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.Builder addSnakesBuilder(
          int index) {
        return getSnakesFieldBuilder().addBuilder(
            index, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.getDefaultInstance());
      }
      /**
       * <code>repeated .messages.Update.PSnake snakes = 4;</code>
       */
      public java.util.List<com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.Builder> 
           getSnakesBuilderList() {
        return getSnakesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.Builder, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnakeOrBuilder> 
          getSnakesFieldBuilder() {
        if (snakesBuilder_ == null) {
          snakesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnake.Builder, com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update.PSnakeOrBuilder>(
                  snakes_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          snakes_ = null;
        }
        return snakesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:messages.Update)
    }

    // @@protoc_insertion_point(class_scope:messages.Update)
    private static final com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update();
    }

    public static com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Update>
        PARSER = new com.google.protobuf.AbstractParser<Update>() {
      public Update parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Update(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Update> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Update> getParserForType() {
      return PARSER;
    }

    public com.tianyi.zhang.multiplayer.snake.agents.messages.Packet.Update getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Update_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_Update_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Update_PSnake_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messages_Update_PSnake_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014packet.proto\022\010messages\"\366\001\n\006Update\022&\n\005s" +
      "tate\030\001 \002(\0162\027.messages.Update.PState\022\017\n\007v" +
      "ersion\030\002 \002(\005\022\021\n\ttimestamp\030\003 \002(\003\022\'\n\006snake" +
      "s\030\004 \003(\0132\027.messages.Update.PSnake\032L\n\006PSna" +
      "ke\022\n\n\002id\030\001 \002(\005\022\023\n\013lastInputId\030\002 \002(\005\022\021\n\td" +
      "irection\030\003 \002(\005\022\016\n\006coords\030\004 \003(\005\")\n\006PState" +
      "\022\t\n\005READY\020\000\022\024\n\020GAME_IN_PROGRESS\020\001B<\n2com" +
      ".tianyi.zhang.multiplayer.snake.agents.m" +
      "essagesB\006Packet"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_messages_Update_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_Update_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_Update_descriptor,
        new java.lang.String[] { "State", "Version", "Timestamp", "Snakes", });
    internal_static_messages_Update_PSnake_descriptor =
      internal_static_messages_Update_descriptor.getNestedTypes().get(0);
    internal_static_messages_Update_PSnake_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messages_Update_PSnake_descriptor,
        new java.lang.String[] { "Id", "LastInputId", "Direction", "Coords", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
